# Generated by Django 5.2.16 on 2026-07-12 09:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_driver_id_alter_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='maximum_load_capacity',
            field=models.DecimalField(decimal_places=2, help_text='Maximum cargo capacity in kilograms.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
