# Generated by Django 5.2.16 on 2026-07-12 05:40

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_driver_id_alter_vehicle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Registration Certificate'), ('INSURANCE', 'Insurance'), ('PERMIT', 'Permit'), ('PUC', 'Pollution Certificate'), ('FITNESS', 'Fitness Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to=documents.models.vehicle_document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), documents.models.validate_document_size])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['vehicle__registration_number', 'document_type', 'title'],
                'indexes': [models.Index(fields=['document_type'], name='documents_v_documen_658997_idx'), models.Index(fields=['expiry_date'], name='documents_v_expiry__e7c776_idx')],
            },
        ),
    ]
