# Generated by Django 5.2.16 on 2026-07-12 04:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_driver_id_alter_vehicle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Cargo weight in kilograms.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('planned_distance', models.DecimalField(decimal_places=2, help_text='Planned distance in kilometres.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in litres.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='operations__status_87529e_idx'), models.Index(fields=['created_at'], name='operations__created_c196f9_idx'), models.Index(fields=['vehicle', 'status'], name='operations__vehicle_7e52bd_idx'), models.Index(fields=['driver', 'status'], name='operations__driver__356f63_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cargo_weight__gt', 0)), name='trip_cargo_weight_positive'), models.CheckConstraint(condition=models.Q(('planned_distance__gt', 0)), name='trip_distance_positive'), models.CheckConstraint(condition=models.Q(('revenue__gte', 0)), name='trip_revenue_non_negative'), models.UniqueConstraint(condition=models.Q(('status', 'DISPATCHED')), fields=('vehicle',), name='one_active_trip_per_vehicle'), models.UniqueConstraint(condition=models.Q(('status', 'DISPATCHED')), fields=('driver',), name='one_active_trip_per_driver')],
            },
        ),
    ]
